project:
  type: website
  resources:
    - CNAME
    - llms.txt
    - img/optimized/*
  output-dir: docs
  include-in-header:
    - _includes/org-jsonld.html
    - _includes/og-tags.html

execute:
    freeze: auto

website:
  title: "ECLIPSE Lab"  
  favicon: favicon-32x32.png
  open-graph: true
  image: ./img/eclipse_header.png
  twitter-card: 
    creator: "@PhilippPelz"
    image: ./img/eclipse_header.png
  site-url: https://pelzlab.science
  navbar:
    logo: ./img/FAU.png
    logo-href: https://pelzlab.science
    search: true
    tools:
      - icon: ./img/erc_logo.svg
        href: hyperscale.qmd
      - icon: twitter
        href: https://twitter.com/PhilippPelz
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/ECLIPSE-Lab
    right:     #TODO: Outreach   
      - href: hyperscale.qmd
        text: "<img src='img/ERC-LOGO-01.svg' height='30' style='vertical-align: middle; margin-right: 5px;' alt='ERC Logo'/> HyperScaleEM"
      - href: news.qmd
        text: News
      - href: teaching.qmd
        text: Teaching
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research
      - href: research-by-problem.qmd
        text: By Problem
      - href: publications.qmd
        text: Publications
      - href: resources.qmd
        text: Resources
      - href: opportunities.qmd
        text: Opportunities
      - href: contact.qmd
        text: Contact

  page-footer:    
    center: 
      - text: "Imprint"
        href: about.qmd
      - text: "Privacy Notice"
        href: license.qmd
      - text: "Accessibility Statement"
        href: trademark.qmd
  # cookie-consent:
  #   type: express
  #   style: headline
  #   palette: dark
  google-analytics:
    tracking-id: "G-TVZKKP7YNR"  
    anonymize-ip: true  
  repo-url: https://github.com/ECLIPSE-Lab/eclipse-lab.github.io
  repo-actions: [source, issue]

  
format:
  html:
    theme:
      - darkly
      - custom.scss
    css: styles.css
    toc: true
