project:
  type: website
  resources:
    - CNAME
  output-dir: docs

execute:
    freeze: auto

website:
  title: "ECLIPSE Lab"  
  favicon: favicon-32x32.png
  open-graph: true
  twitter-card: 
    creator: "@PhilippPelz"
  site-url: https://pelzlab.science
  navbar:
    logo: ./img/FAU.png
    logo-href: https://pelzlab.science
    background: primary
    search: true
    tools:
      - icon: twitter
        href: https://twitter.com/PhilippPelz
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/ECLIPSE-Lab
    right:     #TODO: Outreach    
      - href: news.qmd
        text: News
      - href: teaching.qmd
        text: Teaching
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: resources.qmd
        text: Resources
      - href: opportunities.qmd
        text: Opportunities
      - href: contact.qmd
        text: Contact
  page-footer:    
    background: "#000000"
    center: 
      - text: "Imprint"
        href: about.qmd
      - text: "Privacy"
        href: license.qmd
      - text: "Accesibility"
        href: trademark.qmd
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-TVZKKP7YNR"  
    anonymize-ip: true  
  repo-url: https://github.com/PhilippPelz/ECLIPSElab
theme:
  light: flatly
  dark: darkly
  
format:
  html:
    theme: darkly
    css: styles.css
    toc: true
