---
pagetitle: "Teaching"
toc: false
email-obfuscation: javascript
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Teaching</li>
  </ol>
</nav>
```
## Winter Semester 2025/2026

- Lecture Materials & Structure (MAP)
  - Fr 10:15h - 11:45h H10
  <!-- - [studon](https://www.studon.fau.de/studon) -->

- Lecture Data Science for Electron Microscopy
  - Fr 12:15h - 13:45h IZNF Rm 01.160
  <!-- - [studon](https://www.studon.fau.de/campo/course/489020) -->
  - [website](https://pelzlab.science/DataScienceForElectronMicroscopy/)

- Seminar Machine Learning for Microscopy
  - Fr 14:15h - 15:45h IZNF Rm 01.160
  <!-- - [studon](https://www.studon.fau.de/campo/course/491599) -->
  - [website](https://pelzlab.science/MachineLearningForMicroscopy/)

## Summer Semester 2025

- Lecture Materials & Structure (Clean Energy Processes)
  - Tue 10:15h - 11:45h Seminar Room 0.68 WW building
  - [studon](https://www.studon.fau.de/studon)

- Lecture Data Science for Electron Microscopy
  - Tue 16:15h - 17:45h IZNF Rm 01.160
  - [studon](https://www.studon.fau.de/campo/course/489020)
  - [website](https://pelzlab.science/DataScienceForElectronMicroscopy/)

- Seminar Machine Learning for Microscopy
  - Thu 16:15h - 17:45h IZNF Rm 01.160
  - [studon](https://www.studon.fau.de/campo/course/491599)
  - [website](https://pelzlab.science/MachineLearningForMicroscopy/)

- Seminar Materials & Structure (Clean Energy Processes)
  - Thu 16:15h - 17:45h Seminar Room 0.68 WW building
  - [studon](https://www.studon.fau.de/studon/ilias.php?baseClass=ilrepositorygui&cmdNode=116:p8&cmdClass=ilObjCourseGUI&cmd=view&ref_id=6216946)
  - [website](https://pelzlab.science/MaterialsAndStructureSeminar/)

## Winter Semester 2024

[Lecture Materials & Structure (MAP): Fr 10:15h - 11:45h Seminar Room 0.68 WW building](https://www.studon.fau.de/studon)

[Lecture Data Science for Electron Microscopy: Fr 8:30h - 10h IZNF Rm 01.160](https://pelzlab.science/DataScienceForElectronMicroscopy/)

[Seminar Machine Learning for Microscopy: Wed 8:30h - 10:00h IZNF Rm 01.140](https://www.studon.fau.de/campo/course/421966)

## Summer Semester 2024

[Lecture Materials & Structure (BSc Clean Energy Processes): Thu 10:15h - 11:45h](https://www.studon.fau.de/studon/goto.php?target=crs_5609585&client_id=StudOn)

[Lecture Data Science for Electron Microscopy: Wed 10:15h - 11:45h IZNF Rm 01.160](https://www.studon.fau.de/campo/course/421992)

[Seminar Machine Learning for Microscopy: Wed 8:30h - 10:00h IZNF Rm 01.160](https://www.studon.fau.de/campo/course/421966)

## Winter Semester 2023

[Lecture Materials & Structure](https://www.studon.fau.de/crs5223702_join.html)

[Lecture Data Science for Electron Microscopy: Tue 8:30h - 10:00h IZNF Rm 01.160](https://www.studon.fau.de/campo/course/401180)

[Seminar Machine Learning for Microscopy: Thu 8:30h - 10:00h IZNF Rm 01.160](https://www.studon.fau.de/campo/course/401181)

## Summer Semester 2023

Lecture Materials & Structure

Lecture Data Science for Electron Microscopy

Seminar Machine Leanring for Microscopy

