---
title: "Photo-double-ionization of ethylene and acetylene near threshold"
type: "article"
author: "B. Gaire, S. Y. Lee, D. J. Haxton, P. M. Pelz, I. Bocharova, F. P. Sturm, N. Gehrken, M. Honig, M. Pitzer, D. Metz, H. Kim, M. Schöffler, R. Dörner, H. Gassert, S. Zeller, J. Voigtsberger, W. Cao, M. Zohrabi, J. Williams, A. Gatton, D. Reedy, C. Nook, T. Müller, A. L. Landers, C. L. Cocke, I. Ben-Itzhak, T. Jahnke, A. Belkacem, T. Weber"
year: "2014"
publication: "Physical Review A 89"
preprint: ""
doi: "10.1103/PhysRevA.89.013403"
materials: ""
code_url: ""
project_page_url: ""
toc: false
categories:
  - journal article
---

## Citation (APA 7)

> Photo-double-ionization of ethylene and acetylene near threshold
B. Gaire, S. Y. Lee, D. J. Haxton, P. M. Pelz, I. Bocharova, F. P. Sturm, N. Gehrken, M. Honig, M. Pitzer, D. Metz, H. Kim, M. Schöffler, R. Dörner, H. Gassert, S. Zeller, J. Voigtsberger, W. Cao, M. Zohrabi, J. Williams, A. Gatton, D. Reedy, C. Nook, T. Müller, A. L. Landers, C. L. Cocke, I. Ben-Itzhak, T. Jahnke, A. Belkacem, T. Weber
Physical Review A 89


## Abstract

Photo double ionization of ethylene and acetylene near threshold B. Gaire, 1 S.Y. Lee, 1 D. J. Haxton, 2 P.M. Pelz, 1 I. Bocharova, 1 F.P. Sturm, 1, 3 N. Gehrken, 1, 3 M. Honig, 3 M. Pitzer, 3 D. Metz, 3 H-K. Kim, 3 M. Sch¨oﬄer, 3 R. D¨orner, 3 H. Gassert, 3 S. Zeller, 3 J. Voigtsberger, 3 W. Cao, 4 M. Zohrabi, 4 J. Williams, 5 A. Gatton, 5 D. Reedy, 5 C. Nook, 5 Thomas M¨ uller, 6 A.L. Landers, 5 C.L. Cocke, 4 I. Ben-Itzhak, 4 T. Jahnke, 3 A. Belkacem, 1 and Th. Weber 1 Chemical Sciences Division, Lawrence Berkeley National Laboratory, Berkeley, CA 94720, USA Chemical Sciences Division and Ultrafast X-Ray Science Laboratory, Lawrence Berkeley National Laboratory, Berkeley, CA 94720, USA Institut f¨ ur Kernphysik, Goethe-Universit¨ at, Max-von-Laue-Str.1, 60438 Frankfurt am Main, Germany J. R. Macdonald Laboratory, Department of Physics, Kansas State University, Manhattan, KS 66506, USA Department of Physics, Auburn University, AL 36849, USA Institute of Advancend Simulation, J¨ ulich Supercomputer Centre, Forschungszentrum J¨ ulich, D-52425 J¨ ulich, Germany (Dated: October 31, 2013) We present kinematically complete measurements of the photo double ionization of ethylene (dou- ble CC bond) and acetylene (triple CC bond) hydrocarbons just above the double ionization thresh- old. We discuss the results in terms of the coincident kinetic energy of the photo electrons and the nuclear kinetic energy release of the recoiling ions. We have incorporated quantum chemistry calculations to interpret which of the electronic states of the dication have been populated and trace the various subsequent fragmentation channels. We suggest pathways that involve the electronic ground and excited states of the precursor ethylene dication and explore the strong inﬂuence of the conical intersections between the diﬀerent electronic states. The nondissociative ionization yield is small in ethylene and high in acetylene when compared with the dissociative ionization channels. The reason for such a striking diﬀerence is explained in part on the basis of a propensity rule which inﬂuences the population of states in the photo double ionization of a centrosymmetric closed shell molecule by favoring singlet ungerade and triplet gerade ﬁnal states. This propensity rule and the calculated potential energy surfaces clarify a picture of the dynamics leading to the observed dication dissociation products. PACS numbers: 33.80.Eh, 33.90.+h I. INTRODUCTION In the Photo Double Ionization (PDI) of a target atom or a molecule, one photon is absorbed by a single electron which then interacts with another electron, ejecting both into the continuum and producing one or more charged recoil ions. The essential interaction of the two electrons make PDI an ideal process for studying electron-electron correlation. Moreover, fragmentation dynamics can be investigated by connecting electronic states to diﬀerent dissociation channels. In past years, PDI has seen ex- tensive study on two electron systems such as H 2 and He with intra shell electron-electron correlation and on many electron diatomic molecules with both intra and in- ter shell electron-electron interactions (see, e.g. Refs. [1– 5]). The natural next step is to use polyatomic molecu- lar targets to explore the eﬀects of chemical bonding on electron-electron correlation. PDI of these targets also oﬀers a variety of avoided crossings and conical intersec- tions of Potential Energy Surfaces (PESs) that produce a rich array of nuclear dynamics during dissociation. We chose to study closed shell hydrocarbon molecules with diﬀerent types of hybridization of their carbon- carbon bond, namely ethylene (C 2 H 4 ) and acetylene (C 2 H 2 ). We expect PDI of these two species to be diﬀer- ent because of their dissimilar geometries and electronic conﬁgurations. The double ionization of these molecules with photon and particle impact has been explored heav- ily in the past both in theory and experiment (ethylene [6–8] and acetylene [9–16]). Previous studies in ethylene include methods like double-charge-transfer spectroscopy [7, 17, 18], charge-stripping-mass spectroscopy [19, 20], Auger spectroscopy [21, 22], and time-of-ﬂight mass spec- trometry [23–25]. In all these experiments the detection of the doubly charged ion C 2 H 4 2+ is elusive. This is due to the fact that the Time Of Flight (TOF) of the molec- ular dication and the fragment ions from other breakup channels overlap. The fragmentation pathways remain unidentiﬁed in these studies and a more sensitive probe is needed to pinpoint the existence of a stable dication in the direct PDI near threshold. Here we utilize a method that allows the coincidence detection of both electrons and the recoil ions produced by double ionization. We choose photon energies close to the PDI threshold where deviations from the Wannier law are expected to be small. By detecting the energies of all particles simultaneously we are able to verify that most electrons are emitted via direct double ionization and that any competing two-step processes such as au- toionization or Auger decay play a minor role. This en- ables the kinematically complete study of the direct PDI


