---
title: "Solving complex nanostructures with ptychographic atomic electron tomography."
type: "article"
author: "Philipp M. Pelz, Sinéad M. Griffin, Scott Stonemeyer, Derek Popple, Hannah DeVyldere, Peter Ercius, Alex Zettl, Mary C. Scott & Colin Ophus"
year: "2023"
publication: "Nat Commun 14, 7906"
preprint: "https://arxiv.org/abs/2206.08958"
doi: "https://doi.org/10.1038/s41467-023-43634-z"
materials: ""
toc: false
categories:
  - 4D-STEM
  - detectors
  - electron microscopy
  - journal article
---

## Citation (APA 7)

> Pelz, P.M., Griffin, S.M., Stonemeyer, S. et al. Solving complex nanostructures with ptychographic atomic electron tomography. Nat Commun 14, 7906 (2023). 



## Abstract

Transmission electron microscopy (TEM) is essential for determining atomic scale structures in structural biology and materials science. In structural biology, three-dimensional structures of proteins are routinely determined from thousands of identical particles using phase-contrast TEM. In materials science, three-dimensional atomic structures of complex nanomaterials have been determined using atomic electron tomography (AET). However, neither of these methods can determine the three-dimensional atomic structure of heterogeneous nanomaterials containing light elements. Here, we perform ptychographic electron tomography from 34.5 million diffraction patterns to reconstruct an atomic resolution tilt series of a double wall-carbon nanotube (DW-CNT) encapsulating a complex ZrTe sandwich structure. Class averaging the resulting tilt series images and subpixel localization of the atomic peaks reveals a Zr11Te50 structure containing a previously unobserved ZrTe2 phase in the core. The experimental realization of atomic resolution ptychographic electron tomography will allow for the structural determination of a wide range of beam-sensitive nanomaterials containing light elements.



